# Generated by Django 6.0.2 on 2026-02-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.AutoField(help_text='Unique ID for each tool.', primary_key=True, serialize=False)),
                ('tool_name', models.CharField(help_text='The name of the tool.', max_length=255, unique=True)),
                ('tool_description', models.TextField(help_text='A description of what the tool does.')),
                ('meta_data', models.JSONField(help_text='A JSON object that defines the required parameters for the tool.')),
            ],
        ),
    ]
